Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: ibm-watson in c:\users\user\appdata\roaming\python\python39\site-packages (5.3.0)
Requirement already satisfied: ibm-cloud-sdk-core==3.*,>=3.3.6 in c:\users\user\appdata\roaming\python\python39\site-packages (from ibm-watson) (3.11.3)
Requirement already satisfied: websocket-client==1.1.0 in c:\users\user\appdata\roaming\python\python39\site-packages (from ibm-watson) (1.1.0)
Requirement already satisfied: requests<3.0,>=2.0 in c:\users\user\appdata\roaming\python\python39\site-packages (from ibm-watson) (2.25.1)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\user\appdata\roaming\python\python39\site-packages (from ibm-watson) (2.8.1)
Requirement already satisfied: PyJWT<3.0.0,>=2.0.1 in c:\users\user\appdata\roaming\python\python39\site-packages (from ibm-cloud-sdk-core==3.*,>=3.3.6->ibm-watson) (2.1.0)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.5.3->ibm-watson) (1.15.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user\appdata\roaming\python\python39\site-packages (from requests<3.0,>=2.0->ibm-watson) (1.26.5)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\user\appdata\roaming\python\python39\site-packages (from requests<3.0,>=2.0->ibm-watson) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\roaming\python\python39\site-packages (from requests<3.0,>=2.0->ibm-watson) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\user\appdata\roaming\python\python39\site-packages (from requests<3.0,>=2.0->ibm-watson) (2.10)
